-- Add 100 daily challenges
INSERT INTO challenges (title, description, type, points, active) VALUES
-- Mood Challenges (25 challenges)
('Morning Mood Check', 'How are you feeling this morning? Take a moment to describe your emotional state and what might be influencing it.', 'mood', 10, true),
('Energy Level Reflection', 'Rate your current energy level and describe what factors are affecting it today.', 'mood', 15, true),
('Emotional Weather Report', 'If your emotions were weather, what would today''s forecast be? Describe your emotional climate.', 'mood', 20, true),
('Mood Color Palette', 'What colors represent your emotions today? Explain why you chose these colors.', 'mood', 15, true),
('Peak Moment', 'Describe the moment today when you felt your best. What made it special?', 'mood', 20, true),
('Stress Awareness', 'Identify your current stress level and what might be causing any tension.', 'mood', 15, true),
('Mood Music', 'What song best represents your current mood? Why does it resonate with you?', 'mood', 20, true),
('Body-Mind Connection', 'How is your physical state affecting your emotional well-being today?', 'mood', 15, true),
('Emotional Growth', 'Compare your mood now to how you felt yesterday. What''s changed?', 'mood', 20, true),
('Mood Triggers', 'Identify something that significantly impacted your mood today.', 'mood', 15, true),
('Evening Reflection', 'How has your mood evolved throughout the day? What influenced any changes?', 'mood', 20, true),
('Emotional Awareness', 'Name three distinct emotions you''ve experienced today and what caused them.', 'mood', 25, true),
('Mood Management', 'What strategies have you used today to maintain or improve your mood?', 'mood', 20, true),
('Social Impact', 'How have your interactions with others affected your mood today?', 'mood', 15, true),
('Environmental Effects', 'How is your environment (weather, space, noise) affecting your mood?', 'mood', 15, true),
('Mood Patterns', 'Have you noticed any patterns in your mood this week?', 'mood', 20, true),
('Emotional Needs', 'What emotional needs are most prominent for you right now?', 'mood', 25, true),
('Mood Metaphor', 'If your mood was an animal, what would it be and why?', 'mood', 20, true),
('Energy Audit', 'What activities energized or drained you today?', 'mood', 15, true),
('Mood Journey', 'Describe your emotional journey through today''s challenges and victories.', 'mood', 25, true),
('Comfort Zone', 'How comfortable are you feeling today? What''s affecting your comfort level?', 'mood', 15, true),
('Emotional Balance', 'Rate your emotional balance today and explain what''s contributing to it.', 'mood', 20, true),
('Mood Influences', 'What external factors are most affecting your mood right now?', 'mood', 15, true),
('Emotional Resilience', 'How well are you bouncing back from challenges today?', 'mood', 25, true),
('Mood Snapshot', 'Take a snapshot of your current emotional state. What do you observe?', 'mood', 15, true),

-- Gratitude Challenges (25 challenges)
('Simple Pleasures', 'What small, everyday thing brought you joy today?', 'gratitude', 10, true),
('Unexpected Kindness', 'Describe an unexpected act of kindness you experienced or witnessed today.', 'gratitude', 15, true),
('Nature''s Gifts', 'What element of nature are you most grateful for today?', 'gratitude', 15, true),
('Personal Growth', 'What personal quality or skill are you thankful for developing?', 'gratitude', 20, true),
('Meaningful Connections', 'Which relationship in your life are you most grateful for today?', 'gratitude', 20, true),
('Daily Comfort', 'What comfort or convenience do you often take for granted?', 'gratitude', 15, true),
('Learning Opportunities', 'What learning experience are you grateful for today?', 'gratitude', 20, true),
('Health Appreciation', 'What aspect of your health are you most thankful for?', 'gratitude', 15, true),
('Support System', 'Who has supported you recently? How are you grateful for them?', 'gratitude', 20, true),
('Personal Achievement', 'What recent accomplishment, big or small, are you grateful for?', 'gratitude', 25, true),
('Home Comforts', 'What about your living space are you most thankful for?', 'gratitude', 15, true),
('Work Appreciation', 'What aspect of your work or studies brings you gratitude?', 'gratitude', 20, true),
('Food Gratitude', 'What meal or food experience are you thankful for today?', 'gratitude', 15, true),
('Technology Thanks', 'Which piece of technology are you particularly grateful for?', 'gratitude', 15, true),
('Past Lessons', 'What past challenge are you now grateful for?', 'gratitude', 20, true),
('Future Hope', 'What upcoming opportunity are you thankful for?', 'gratitude', 15, true),
('Self-Care', 'What self-care practice are you grateful to have in your life?', 'gratitude', 20, true),
('Creative Expression', 'What form of creativity or self-expression are you thankful for?', 'gratitude', 25, true),
('Daily Tools', 'What everyday object are you particularly grateful for today?', 'gratitude', 15, true),
('Cultural Heritage', 'What aspect of your cultural background brings you gratitude?', 'gratitude', 20, true),
('Personal Freedom', 'What freedom or choice are you most grateful for today?', 'gratitude', 25, true),
('Sensory Joy', 'What sight, sound, or smell are you thankful for experiencing today?', 'gratitude', 15, true),
('Knowledge Access', 'What source of knowledge or information are you grateful for?', 'gratitude', 20, true),
('Physical Ability', 'What physical ability are you particularly thankful for today?', 'gratitude', 15, true),
('Community Connection', 'What aspect of your community brings you gratitude?', 'gratitude', 20, true),

-- Mindfulness Challenges (25 challenges)
('Present Moment', 'Take three deep breaths and describe your current sensations.', 'mindfulness', 15, true),
('Mindful Walking', 'Take a short walk focusing only on your steps and surroundings.', 'mindfulness', 20, true),
('Sound Awareness', 'Close your eyes and list all the sounds you can hear right now.', 'mindfulness', 15, true),
('Body Scan', 'Perform a quick body scan and note any areas of tension or comfort.', 'mindfulness', 20, true),
('Mindful Eating', 'Eat one small thing with complete attention to taste and texture.', 'mindfulness', 25, true),
('Breath Focus', 'Spend two minutes focusing solely on your breath pattern.', 'mindfulness', 15, true),
('Sensory Check-in', 'Name one thing you can see, hear, feel, smell, and taste.', 'mindfulness', 20, true),
('Thought Observation', 'Watch your thoughts pass by like clouds for three minutes.', 'mindfulness', 25, true),
('Emotional Awareness', 'Sit quietly and observe your emotions without judgment.', 'mindfulness', 20, true),
('Physical Presence', 'Focus on how your body feels in your current position.', 'mindfulness', 15, true),
('Mindful Movement', 'Do a simple stretch while focusing on body sensations.', 'mindfulness', 20, true),
('Nature Connection', 'Spend a moment observing something natural near you.', 'mindfulness', 15, true),
('Mindful Touch', 'Focus on the texture of three different objects.', 'mindfulness', 20, true),
('Silent Moment', 'Find a quiet space and sit in silence for two minutes.', 'mindfulness', 25, true),
('Heart Awareness', 'Place your hand on your heart and feel its rhythm.', 'mindfulness', 15, true),
('Mindful Listening', 'Listen to a short piece of music with complete attention.', 'mindfulness', 20, true),
('Visual Focus', 'Choose an object and observe its details for one minute.', 'mindfulness', 15, true),
('Emotional Weather', 'Observe your emotional state without trying to change it.', 'mindfulness', 20, true),
('Mindful Hands', 'Focus on the sensations in your hands for one minute.', 'mindfulness', 15, true),
('Breathing Space', 'Take a three-minute breathing space break.', 'mindfulness', 20, true),
('Present Awareness', 'List five things happening in this exact moment.', 'mindfulness', 25, true),
('Body Boundaries', 'Notice where your body makes contact with your surroundings.', 'mindfulness', 15, true),
('Thought Pause', 'Take a moment to pause and watch your thoughts.', 'mindfulness', 20, true),
('Sensory Journey', 'Focus on each of your senses one at a time.', 'mindfulness', 25, true),
('Mindful Posture', 'Notice and adjust your posture mindfully.', 'mindfulness', 15, true),

-- Creative Challenges (25 challenges)
('Word Picture', 'Describe your current mood using only metaphors and similes.', 'creative', 25, true),
('Emotion Color', 'Create a short story about your favorite color and its meaning to you.', 'creative', 30, true),
('Memory Snapshot', 'Write a vivid description of your most cherished memory.', 'creative', 25, true),
('Future Letter', 'Write a letter to your future self about your current hopes.', 'creative', 30, true),
('Dream Journal', 'Describe a recent dream or daydream in creative detail.', 'creative', 25, true),
('Nature Story', 'Write a short story from the perspective of a natural object.', 'creative', 30, true),
('Emotion Poetry', 'Create a short poem about your strongest emotion today.', 'creative', 35, true),
('Character Sketch', 'Write a character description of someone who inspires you.', 'creative', 30, true),
('Sensory Scene', 'Describe a scene using all five senses.', 'creative', 25, true),
('Dialogue Creation', 'Write a dialogue between two emotions you''re feeling.', 'creative', 30, true),
('Adventure Tale', 'Write about an everyday activity as an epic adventure.', 'creative', 35, true),
('Object Story', 'Tell the story of an important object in your life.', 'creative', 25, true),
('Mood Music', 'Describe your perfect soundtrack for today.', 'creative', 30, true),
('Future Scene', 'Write a scene from your ideal future.', 'creative', 35, true),
('Personal Myth', 'Create a myth or legend about your life journey.', 'creative', 40, true),
('Weather Emotions', 'Write about your emotions as if they were weather patterns.', 'creative', 30, true),
('Time Capsule', 'Describe what you''d put in a time capsule today.', 'creative', 25, true),
('Animal Perspective', 'Write about your day from a pet''s perspective.', 'creative', 30, true),
('Taste Memory', 'Write about a memory triggered by a specific taste.', 'creative', 25, true),
('Sound Story', 'Create a story inspired by a sound you can hear right now.', 'creative', 30, true),
('Place Description', 'Write about a place that makes you feel peaceful.', 'creative', 25, true),
('Conversation Scene', 'Write a scene of an important conversation in your life.', 'creative', 35, true),
('Journey Tale', 'Describe a personal journey as a hero''s quest.', 'creative', 40, true),
('Gratitude Story', 'Write a creative story about something you''re grateful for.', 'creative', 30, true),
('Life Chapter', 'Write the current chapter of your life as if it were a book.', 'creative', 35, true); 